name: SVLint Check

on:
  push:
  pull_request:

jobs:
  svlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install svlint
        run: |
          cargo install svlint

      - name: Run svlint
        run: |
          svlint rtl/*.v tests/*.v